version: '2'

services:
    nginx:
        image: nginx
       # command: "rm /etc/nginx/conf.d/default.conf"
        volumes:
          - ./nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 8080:80
            
        restart: always

    node:
        depends_on:
            - nginx
        image: "node:8"
        user: "node"
        working_dir: /home/node/app
        environment:
          - NODE_ENV=dev
        volumes:
          - ./:/home/node/app
        ports:
          - "8081:3001"
        command: "node hello.js"
        restart: always
